services:
    app-mssql:
        image: microsoft/mssql-server-linux:latest
        # volumes are not supported on macOS
        # uncomment bellow volume and replace volume with relative or absolute path of the host
        # volumes:
        #     - ~/volumes/jhipster/tempdb/mssql/:/var/opt/mssql/data/
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password
        ports:
            - 1433:1433